PinProjekt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//dodajemo da možemo koristit svoju bazu
using PinProjekt.Models;

namespace PinProjekt.Controllers
{
    public class HomeController : Controller
    {
        // bazi pristupamo sa db
        DBuserSignupLoginEntities db = new DBuserSignupLoginEntities();
        DBartikliEntities dbart = new DBartikliEntities();
        // GET: Home
        public ActionResult Index()
        {
            using(dbart)
            {
                return View(dbart.TBLartiklis.ToList());
            }
         
        }

        // Akcija za klik na Signup
        public ActionResult Registracija()
        {
            return View();
        }

        [HttpPost]
        // prima tip podatka "imetablice" imeVarijable koje korisnik šalje 
        public ActionResult Registracija(TBLUserInfo tBLUserInfo)
        {

            // ispitujemo da li u bazi postoji več user koji se opet želi registrirati, a ako ne postoji dodajemo ga u bazu
            if(db.TBLUserInfoes.Any(x=>x.UsernameUs == tBLUserInfo.UsernameUs))
            {
                // da bi se ovo vidlo moramo ići na View od Signup-a i dodati div class="form-group" na kraju sa lablelom @ViewBag.Notification
                ViewBag.Notification = "Ovaj korisnik je već registriran";
                return View();
            }
            else
            {
                db.TBLUserInfoes.Add(tBLUserInfo);
                db.SaveChanges();

                //Treba nam za provjeru i linkanje na layout-u da ga možemomodificirati 
                Session["IdUsSS"] = tBLUserInfo.IdUs.ToString();
                Session["UsernameSS"] = tBLUserInfo.UsernameUs.ToString();

                return RedirectToAction("Index", "Home");

            }
        }

        // Akcija za Logut Vrati na index i počisti sešn
        public ActionResult Odjava()
        {
            // Čišćenje sešna 
            Session.Clear();
            // umjesto vračanja View-a možemo navesti koji točno da se izvede
            return RedirectToAction("Index", "Home");
        }
        
        //Akcija za Login -> novi View za login
        [HttpGet]
        public ActionResult Prijava()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Prijava(TBLUserInfo tBLUserInfo)
        {
            
            //FristorDefalut vrača prvi element ili default vrijednost ako propadne
            var checkLogin = db.TBLUserInfoes.Where(x => x.UsernameUs.Equals(tBLUserInfo.UsernameUs) && x.PasswordUs.Equals(tBLUserInfo.PasswordUs)).FirstOrDefault();
            
            if(tBLUserInfo.UsernameUs == "Admin")
            {
                // moramo stavit u string da možemo ispitat jel null - npr u Shared -> _Layout 
                Session["UsernameSS"] = tBLUserInfo.UsernameUs.ToString();
                return RedirectToAction("skladiste", "skladiste");
                
            }
            else if(checkLogin != null)
            {
                Session["IdUsSS"] = tBLUserInfo.IdUs.ToString();
                Session["UsernameSS"] = tBLUserInfo.UsernameUs.ToString();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Notification = "Krivo korisničko ime ili lozinka.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Kontakt()
        {
            return View();
        }


    }
}

PinProjekt/Controllers/kosaricaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PinProjekt.Models;
namespace PinProjekt.Controllers
{
    public class kosaricaController : Controller
    {
        DBartikliEntities dbart = new DBartikliEntities();
        DBuserSignupLoginEntities db = new DBuserSignupLoginEntities();
        // GET: kosarica
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dodaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dodaj(TBLartikli tBLartikli)
        {
            int kosarica = 0; 
            if(tBLartikli.kolicina > 2)
            {
                return RedirectToAction("Registracija", "Home");
            }
             else
            {
                kosarica = 2;
            }
            return View();
        }
    }
}

PinProjekt/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>O nama</h2>
<p>Osnovani smo 2015g. na brdu iznad Dubrave. Jednostavno u društvu dobrih prijatelja</p>
<p>rodila se ideja koja je imala potencijala i krenuli smo u realizaciju, i danas smo tu zadovoljni</p>
<p>svojim postignuićem.</p>

PinProjekt/Views/Home/Index.cshtml
@model IEnumerable<PinProjekt.Models.TBLartikli>

@{
    ViewBag.Title = "Index";
}

<h2>Dučan</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.sifra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kolicina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.slika)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.sifra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cijena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kolicina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.opis)
        </td>
        <td>  
            <img src="@Html.DisplayFor(modelItem => item.slika)" width="100px" height="100px"/>
        </td>
        <td>
            @Html.ActionLink("Kupi", "Dodaj","kosarica")

        </td>
    </tr>
}

</table>

PinProjekt/Views/Home/Kontakt.cshtml
@{
    ViewBag.Title = "Kontakt";
}

<h2>Kontakt</h2>

<p>Telefon: 01/2783-102</p>
<p>Mobitel: 091/2223-123</p>
<p>Email uprava: uprava@kli-kla.hr</p>
<p>Email Shop: nabava@kli-kla.hr</p>

PinProjekt/Views/Home/Prijava.cshtml
@model PinProjekt.Models.TBLUserInfo

@{
    ViewBag.Title = "Prijava";
}

<h2>Prijava</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
 
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.UsernameUs, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UsernameUs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UsernameUs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PasswordUs, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PasswordUs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PasswordUs, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

    <!--Za ispisivanje greške -->
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label>@ViewBag.Notification</label>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("U dučan", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PinProjekt/Views/Home/Registracija.cshtml
@model PinProjekt.Models.TBLUserInfo

@{
    ViewBag.Title = "Registracija";
}

<h2>Registracija</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.UsernameUs, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UsernameUs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UsernameUs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PasswordUs, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PasswordUs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PasswordUs, "", new { @class = "text-danger" })
        </div>
    </div>
    <!--Dodajemo dodatni  div za vizual potvrde lozinke kopiranjem diva iznad i promjenom model.RePasswordUS na 3 mjesta-->
    <div class="form-group">
        @Html.LabelFor(model => model.RePasswordUs, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RePasswordUs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RePasswordUs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <!--Za poruku greške-->
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label>@ViewBag.Notification</label>
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("U dučan", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}